using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectManagement.Routes
{
    public class EvolutionRouter
    {
        public static string GetEvolution = "https://my-first-web-1nodejs.herokuapp.com/evolution";
        public static string PostEvolution = "https://my-first-web-1nodejs.herokuapp.com/evolution/add";
    }
}
